#+TITLE: touchesc

Broadcast data received from touche sweep frequency capacitive sensing system
to a list of local actions and network OSC clients.

* Installation

1. Download and install SuperCollider 3.x. (http://supercollider.sourceforge.net/downloads/).

2. If this is the first time you use SuperCollider, then start the SuperCollider application.  This will create the SuperCollider user support directory.

3. In SuperCollider, choose from menu "File" the item "Open user support directory".

4. In the user support directory, create a new folder "Extensions" (if that folder does not already exist).

5. Drag the folder of the present library ("touchesc") into the "Extensions" folder.  You can also drag an alias (shortcut) of the "touchesc" folder instead into Extensions, instead of the folder itself.

6. Download library "tiny-sc" from https://github.com/iani/tiny-sc/.  Direct link: https://github.com/iani/tiny-sc/archive/master.zip

7. Install tiny-sc by putting it "Extensions" as in step 5 above.

8. Start SuperCollider, or if SuperCollider is already running, then recompile the library (Menu "Language", item "Recompile Class Library").

* Use
:PROPERTIES:
:ID:       CC4430C2-2891-46DA-B3B8-CECAB44511FB
:eval-id:  2
:END:

Immediately after startup or recompile, touchesc creates a GUI window at the bottom left corner of the screen.  If this window is not visible because it is hidden from the editor (IDE) window, then switch to the application "sclang", or resize the editor window so that you can see the left part of the screen.

The items in the ToucheSC GUI window are (from top to bottom):

1. Button "Find Serial Input Device"": This button lets SC scan all serial ports and attempt to find a port whose name matches the expression "/dev/tty.usb*".  This is the default usb port on MacOS (Linux?  Windows?).  If a matching port is found, then ToucheSC sets itself to open and listen on that port.  Otherwise a warning is issued on the post window.  In that case, edit the text field below the "Find Serial Input Device" button and type "return" ("enter") to make ToucheSC use the new name for finding the USB port.
2. Text field below "Find Serial Input Device":  Displays the name of the USB serial port, that will be used for input.  This name is updated by pushing the button "Find Serial Input Device".  See point 1 above about using this field.
3. Button "Load host IP list".  Click this button to open a dialog box for loading the list of IPs to which the data from the Arduino will be broadcast.  The default list that is shared by members of a network should contain the IPs and port numbers for all computers in that want to share data through ToucheSC.  Additionally, this list may be edited to IPs and port numbers for sending to other software such as Processing, PD, Max, Grasshopper etc. on the local host computer (the computer that is running the local copy of the ToucheSC application).   See example below
4. Start button: This button opens the serial port defined by 2 above, and starts a loop that reads incoming bytes as soon as they arrive.
5. Display field "not running": This field displays the values of the bytes received from arduino once the polling loop starts.
6. Button NOTOUCH: Click to calibrate no-touch state.
7. Button TOUCH: Click to calibrate touch state
8. Button GRAB: Click to calibrate no-touch state
9. Button SAVE: Click to save calibration on eprom.  Arduino will retain the settings when disconnected from power.

*** Example of Host IP List file

#+BEGIN_EXAMPLE
[
NetAddr("127.0.0.1", 10000),
NetAddr("169.254.235.246", 57120),
]
#+END_EXAMPLE

Comments on the above:

: NetAddr("127.0.0.1", 10000),

This sends the messages to the computer that is running the current local copy of ToucheSC ("localhost"), at port 10000.  You can change this number to send osc messages to a different application on your own computer, or you may even add multiple applications, for example like this:


: NetAddr("127.0.0.1", 10000),
: NetAddr("127.0.0.1", 9001),

IP numbers other than "127.0.0.1" send to other computers in the network.  For example:

: NetAddr("169.254.235.246", 57120),

This sends to a computer that has the IP number "169.254.235.246", on port 57120.  57120 is the default port of the SuperCollider language application (sclang).   If you want to send to another port, you may edit this.  Generally, both the IP and the port numbers for remote hosts should be handled centrally by one administrator of the network.

*
